config/routes.rb
Rails.application.routes.draw do

  # Create
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"


  # Read
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks", to: "tasks#index"

  # Update
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"

  # Delete
  delete "tasks/:id", to: "tasks#destroy", as: :task_destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end


  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit task </h1>

<%= form_for(@task) do |t| %>
<%= t.label :title %>
<%= t.text_field :title %>
<%= t.label :details %>
<%= t.text_field :details %>
<%= t.label :completed %>
<%= t.check_box :completed %>
<%= t.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do | task | %>
    <li>
    <input type="checkbox"
      <% if task.completed  %>
      checked
      <% end %>
    >
    <%= link_to task.title, task_path(task.id) %>
-
    <%= link_to "Delete",
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
            </li>
  <% end %>
</ul>

<%= link_to "Create Task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create new tasks</h1>

<%= form_for(@task) do |t| %>
<%= t.label :title %>
<%= t.text_field :title %>
<%= t.label :details %>
<%= t.text_field :details %>
<%= t.submit %>
<% end %>


<%= link_to "back to list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed  %>
<input type="checkbox" checked />
<p>This task is completed</p>
<% else  %>
<input type="checkbox" />
<p>This task needs to be completed</p>
<% end %>

<%= link_to "Back to list", tasks_path %>
<%= link_to "Edit Task", task_edit_path(@task) %>